[package]
name = "my-tui-app"
version = "0.1.0"
authors = ["tharindu <chathurangewdt@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "1"
chrono = "0.4"

